version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5500:5500"
    environment:
      - FLASK_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
